# Generated by Django 4.2.7 on 2023-12-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlogoutrecord',
            name='total_time',
            field=models.FloatField(default=0),
        ),
    ]
